#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python -m debugpy --listen 0.0.0.0:5678 --wait-for-client
exec  uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
