#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

# This script checks if the container is started for the first time.
CONTAINER_FIRST_STARTUP="CONTAINER_FIRST_STARTUP"
if [ ! -e /$CONTAINER_FIRST_STARTUP ]; then
    echo "Executing commands first time the container is started"
    touch /$CONTAINER_FIRST_STARTUP
    pip install debugpy
    pip install django-tables2==2.7.5 --no-deps
    python manage.py oscar_populate_countries --no-shipping || true
    python manage.py rebuild_index --noinput # django-haystack
fi

# Async configuration
exec python -m debugpy --listen 0.0.0.0:5678 -m uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'

# Sync live reload
# python manage.py livereload
# exec python -m debugpy --listen 0.0.0.0:5678 manage.py runserver_plus 0.0.0.0:8000
