# Generated by Django 4.2.23 on 2025-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_auto_20210224_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='name',
            field=models.CharField(help_text='This will be shown in the checkout and basket once the coupon is entered', max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='voucherset',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Number of coupons'),
        ),
    ]
