# Generated by Django 4.2.23 on 2025-06-19 23:54

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_alter_voucher_name_alter_voucherset_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='voucherset',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
    ]
