# Generated by Django 4.2.21 on 2025-06-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Names'),
        ),
    ]
