# Generated by Django 4.2.23 on 2025-06-19 23:54

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True),
        ),
    ]
