# Generated by Django 4.2.21 on 2025-06-04 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import oscar.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Code can be used to store a secondary unique identifier, when upc isn't sufficient"),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.SmallIntegerField(db_index=True, default=0, help_text='The highest priority products are shown first', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(max_length=255, upload_to=oscar.utils.models.get_image_upload_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product', verbose_name='Recommended product'),
        ),
    ]
