# Generated by Django 4.2.22 on 2025-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_product_code_product_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommendation',
            name='ranking',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=0, help_text='Determines order of the products. A product with a higher value will appear before one with a lower ranking.', null=True, verbose_name='Ranking'),
        ),
    ]
