# Generated by Django 4.2.22 on 2025-06-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_alter_productcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommendation',
            name='primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='catalogue.product', verbose_name='Primary product'),
        ),
    ]
