#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Create core if it doesn't exist
if [[ ! -d /var/solr/data/oscar_data ]]; then
  /opt/solr/bin/solr create -c oscar_data -n basic_config
fi

exec "$@"
