#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
pip install django-tables2==2.7.5 --no-deps
python manage.py oscar_populate_countries --no-shipping || true
python manage.py rebuild_index --noinput # django-haystack

# Async configuration
# exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn_worker.UvicornWorker

# exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
