# Generated by Django 4.2.22 on 2025-06-05 13:23

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postcode',
            field=oscar.models.fields.UppercaseCharField(blank=True, max_length=11, verbose_name='Post/Zip-code'),
        ),
    ]
