# Generated by Django 4.2.23 on 2025-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_range_excluded_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='max_affected_items',
            field=models.PositiveIntegerField(blank=True, help_text='Set this to prevent the discount consuming all items within the range that are in the basket.aaaaa', null=True, verbose_name='Max Affected Items'),
        ),
    ]
