# Generated by Django 4.2.23 on 2025-06-19 23:54

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_alter_benefit_max_affected_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='range',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
